---
abstract: "A Perl wrapper to the MySource Matrix(TM)/Squiz Matrix(TM) SOAP API.\r"
author:
  - jeffery@astraaustralis.com.au
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Net::MySourceMatrix
name: Net-MySourceMatrix
no_index:
  directory:
    - inc
    - t
requires:
  MIME::Base64: 3.13
  SOAP::Lite: 0.712
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
